/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resolve */
        get: operations["resolve_api_resolve_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/{platform}/{uid}/track": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Track Player
         * @description Idempotent. 409 when the tracked-player cap is full.
         */
        post: operations["track_player_api_players__platform___uid__track_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/{platform}/{uid}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Player History
         * @description Snapshot series for charts, oldest first. days is capped by history_max_days.
         */
        get: operations["player_history_api_players__platform___uid__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/{platform}/{uid}/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Player Matches
         * @description Derived matches, newest first. One row can stand for more than one match.
         */
        get: operations["player_matches_api_players__platform___uid__matches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/{platform}/{uid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Player Profile */
        get: operations["player_profile_api_players__platform___uid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sitemap/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sitemap Players
         * @description Tracked players, the only profiles the sitemap lists.
         */
        get: operations["sitemap_players_api_sitemap_players_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta/maps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Meta Maps
         * @description Current and next map for pubs and ranked, cached for a minute.
         */
        get: operations["meta_maps_api_meta_maps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta/predator": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Meta Predator
         * @description Rank score needed for Predator on each platform, cached for 15 minutes.
         */
        get: operations["meta_predator_api_meta_predator_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ErrorResponse */
        ErrorResponse: {
            /** Detail */
            detail: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            status: components["schemas"]["HealthStatus"];
            /** Database */
            database: boolean;
            /** Worker Alive */
            worker_alive: boolean;
            /** Worker Heartbeat At */
            worker_heartbeat_at: string | null;
        };
        /**
         * HealthStatus
         * @enum {string}
         */
        HealthStatus: "ok" | "degraded" | "down";
        /** HistoryPoint */
        HistoryPoint: {
            /**
             * Taken At
             * Format: date-time
             */
            taken_at: string;
            /** Level */
            level: number;
            /** Level Prestige */
            level_prestige: number;
            /** Level Progress */
            level_progress: number;
            /** Rank Score */
            rank_score: number | null;
            /** Selected Legend */
            selected_legend: string | null;
            /** Trackers */
            trackers: {
                [key: string]: number;
            };
        };
        /** HistoryResponse */
        HistoryResponse: {
            /** Points */
            points: components["schemas"]["HistoryPoint"][];
            /** Bucketed */
            bucketed: boolean;
        };
        /** MapRotation */
        MapRotation: {
            battle_royale?: components["schemas"]["ModeRotation"] | null;
            ranked?: components["schemas"]["ModeRotation"] | null;
        };
        /** MapSlot */
        MapSlot: {
            /** Map */
            map: string;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
        };
        /** MatchItem */
        MatchItem: {
            /** Id */
            id: number;
            kind: components["schemas"]["MatchKind"];
            /**
             * Detected At
             * Format: date-time
             */
            detected_at: string;
            /** Legend */
            legend: string | null;
            /** Level Progress Delta */
            level_progress_delta: number | null;
            /** Rank Score Delta */
            rank_score_delta: number | null;
            /** Tracker Deltas */
            tracker_deltas: {
                [key: string]: number;
            };
        };
        /**
         * MatchKind
         * @enum {string}
         */
        MatchKind: "match" | "session_gap";
        /** MatchesResponse */
        MatchesResponse: {
            /** Items */
            items: components["schemas"]["MatchItem"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** ModeRotation */
        ModeRotation: {
            current: components["schemas"]["MapSlot"];
            next?: components["schemas"]["MapSlot"] | null;
        };
        /**
         * PlatformSlug
         * @description Platform as it appears in URLs.
         * @enum {string}
         */
        PlatformSlug: "pc" | "ps" | "xbox";
        /** PlayerProfile */
        PlayerProfile: {
            /** Uid */
            uid: string;
            platform: components["schemas"]["PlatformSlug"];
            /** Name */
            name: string;
            /** Level */
            level: number;
            /** Level Prestige */
            level_prestige: number;
            /** Level Progress */
            level_progress: number;
            /** Rank Name */
            rank_name: string | null;
            /** Rank Div */
            rank_div: number | null;
            /** Rank Score */
            rank_score: number | null;
            /** Selected Legend */
            selected_legend: string | null;
            /** Trackers */
            trackers: {
                [key: string]: number;
            };
            /** Is Tracked */
            is_tracked: boolean;
            /** Tracked Since */
            tracked_since: string | null;
            /**
             * Last Updated
             * Format: date-time
             */
            last_updated: string;
            /** Stale */
            stale: boolean;
        };
        /** PredatorResponse */
        PredatorResponse: {
            pc: components["schemas"]["PredatorThreshold"] | null;
            ps: components["schemas"]["PredatorThreshold"] | null;
            xbox: components["schemas"]["PredatorThreshold"] | null;
        };
        /** PredatorThreshold */
        PredatorThreshold: {
            /** Rank Score */
            rank_score: number;
            /** Masters And Preds */
            masters_and_preds: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ResolveResponse */
        ResolveResponse: {
            /** Uid */
            uid: string;
            platform: components["schemas"]["PlatformSlug"];
            /** Name */
            name: string;
        };
        /** SitemapPlayer */
        SitemapPlayer: {
            platform: components["schemas"]["PlatformSlug"];
            /** Uid */
            uid: string;
            /** Last Updated */
            last_updated: string | null;
        };
        /** SitemapResponse */
        SitemapResponse: {
            /** Players */
            players: components["schemas"]["SitemapPlayer"][];
        };
        /** TrackResponse */
        TrackResponse: {
            /** Is Tracked */
            is_tracked: boolean;
            /**
             * Tracked Since
             * Format: date-time
             */
            tracked_since: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    resolve_api_resolve_get: {
        parameters: {
            query: {
                platform: components["schemas"]["PlatformSlug"];
                name: string;
            };
            header?: {
                "X-Internal-Token"?: string | null;
                "X-Client-IP"?: string | null;
                "X-Client-User-Agent"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolveResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    track_player_api_players__platform___uid__track_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Internal-Token"?: string | null;
                "X-Client-IP"?: string | null;
                "X-Client-User-Agent"?: string | null;
            };
            path: {
                platform: components["schemas"]["PlatformSlug"];
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    player_history_api_players__platform___uid__history_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: {
                "X-Internal-Token"?: string | null;
            };
            path: {
                platform: components["schemas"]["PlatformSlug"];
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    player_matches_api_players__platform___uid__matches_get: {
        parameters: {
            query?: {
                limit?: number;
                before?: string | null;
            };
            header?: {
                "X-Internal-Token"?: string | null;
            };
            path: {
                platform: components["schemas"]["PlatformSlug"];
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchesResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    player_profile_api_players__platform___uid__get: {
        parameters: {
            query?: never;
            header?: {
                "X-Internal-Token"?: string | null;
                "X-Client-IP"?: string | null;
                "X-Client-User-Agent"?: string | null;
            };
            path: {
                platform: components["schemas"]["PlatformSlug"];
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerProfile"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    sitemap_players_api_sitemap_players_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Internal-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SitemapResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    meta_maps_api_meta_maps_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Internal-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapRotation"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    meta_predator_api_meta_predator_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Internal-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredatorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
